server:
  port: 9090

security:
  basic:
    enabled: true # 启用身份认证
  user:
    name: root # 定义用户名
    password: 123456 # 定义密码

eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost        #eureka服务端实例名称
  client:
    registerWithEureka: false   # false表示自己就是注册中心。我的职责就是维护服务实例，并不需要去检索服务
    fetchRegistry: false        # false表示自己不需要向注册中心注册自己
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/   # 设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址(单机版)
      #defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/   # 集群版
  server:
    enable-self-preservation: false    #由于eureka自我保护机制以及心跳周期长的原因，会出现eureka不剔除已关闭的节点问题
    eviction-interval-timer-in-ms: 5000

